#!/usr/bin/env bash

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart
